### PR TITLE
Update MadelineProto

### PR DESCRIPTION
**Pull request by danog**

### CODE REVIEW

**Comment by setiawanhu** [comment]
Hi @danog !

Thank you for your support on this wrapper library.

I've done some basic smoke test (login -> submit phone code -> send messages -> logout) using version 6 locally, but somehow I'm still experiencing the same issues as [Alimin](https://github.com/danog/MadelineProto/issues/943).

I think I need more time to do other tests and make sure that the changes do not affect others who are currently using this wrapper library.

Regards!

**Comment by irazasyed** [comment]
Any updates on this PR, please?

**Comment by danog** [comment]
Are you still getting this issue?
I've finally released MadelineProto 6, you should give it a try now.

**Review by myscode — APPROVED** [review]

**Comment by setiawanhu** [comment]
Hello, I re-did some tests and it looks good to me

*sorry for the wait :smiley:

**Pull request merged**
